######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 25 00:26:44 2014
######################################################################

TEMPLATE = app
TARGET   = rgb2png
CONFIG      += console
# abitily debbuging with gdb version less 7.5
QMAKE_CXXFLAGS_DEBUG += -gdwarf-3
DEPENDPATH  += .
INCLUDEPATH += .
HEADERS += rgbfile.h
SOURCES += rgb2png.cpp rgbfile.cpp
