######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 25 00:26:44 2014
######################################################################

TEMPLATE = app
TARGET   = tstoimg
CONFIG  += console
HEADERS += rgbfile.h bcellfile.h bsv3file.h
SOURCES += rgbfile.cpp bcellfile.cpp bsv3file.cpp tstoimg.cpp

SOURCES += QVideoEncoder.cpp
LIBS += -lavutil -lavcodec -lavformat -lswscale
