######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 25 00:26:44 2014
######################################################################

TEMPLATE = app
TARGET   = tstoimg
CONFIG  += console
HEADERS += rgbfile.h
SOURCES += tstoimg.cpp rgbfile.cpp
